CC = gcc
CFLAGS = -Wall -I "../../debugging" -I "../../rawIO15" -I "../../sofs15"
IFUNCS1 = soAllocInode.o soFreeInode.o soAllocDataCluster.o soFreeDataCluster.o

all:			ifuncs1

ifuncs1:		$(IFUNCS1)
