CC = gcc
CFLAGS = -Wall -I "../../debugging" -I "../../rawIO15" -I "../../sofs15"
IFUNCS2 = soReadInode.o soWriteInode.o soAccessGranted.o

all:			ifuncs2

ifuncs2:		$(IFUNCS2)

clean:
			rm -f $(IFUNCS2)
