/**
 *  \file monGameOfRopeDS.c (implementation file)
 *
 *  \brief Problem name: Game of the rope.
 *
 *  \brief Concept: Pedro Mariano
 *
 *  Synchronization based on monitors.
 *  Both threads and the monitor are implemented using the pthread library which enables the creation of a
 *  monitor of the Lampson / Redell type.
 *
 *  Monitor internal data structure is made visible so that the students can develop and test separately the operations
 *  carried out by the referee, the coaches and the contestants.
 *
 *  Definition of monitor internal data structure.
 *
 *  \author António Rui Borges - November 2015
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <unistd.h>
#include <math.h>
#include <pthread.h>

#include "probConst.h"
#include "probDataStruct.h"
#include "logging.h"

/** \brief full state of the problem */
FULL_STAT fSt;

/** \brief referee proceed sync point */
pthread_cond_t proceed;

/** \brief coaches waiting for notice sync point array (one per coach) */
pthread_cond_t waitForNotice[C];

/** \brief contestants waiting for command sync point array (one per contestant) */
pthread_cond_t waitForCommand[C][N];

/** \brief number of inform requests generated by the coaches */
unsigned int nCoaches;

/** \brief number of inform requests generated by the contestants after a pulling effort on the rope */
unsigned int nContestants;

/** \brief flags signalling the intention of the referee to command team assembly */
bool chooseTeam[C];

/** \brief number of contestants in position */
unsigned int nContInPosition[C];

/** \brief flags signalling the intention of the referee to inform about the trial outcome */
bool trialDecision[C];

/** \brief flags signalling the intention of the coach to select a contestant to next trial */
bool joinTheTeam[C][N];

/** \brief flags signalling the intention of the referee to inform the contestants it is time to start the trial */
bool startPulling[C][N];

/** \brief flags signalling the intention of the referee to inform the contestants it is time to return to the bench */
bool returnToBench[C][N];

/** \brief locking flag which warrants mutual exclusion inside the monitor */
pthread_mutex_t accessCR = PTHREAD_MUTEX_INITIALIZER;

/** \brief flag which warrants internal data is initialized exactly once */
pthread_once_t init = PTHREAD_ONCE_INIT;;

/** \brief logging file name */
extern char nFic[51];

/**
 *  \brief Internal monitor operation.
 *
 *  Initialization of the internal data structure that contains the shared information and of the logging file.
 */

void initialization (void)
{
  unsigned int n, m, c, g, t;                                                                  /* counting variables */

  /* initialize problem internal status and synchronization points */

  fSt.st.refereeStat = START_OF_THE_MATCH;                                      /* the referee is starting the match */
  for (c = 0; c < C; c++)
    fSt.st.coachStat[c] = WAIT_FOR_REFEREE_COMMAND;                  /* the coach is waiting for the referee command */
  for (c = 0; c < C; c++)
  for (n = 0; n < N; n++)
  { fSt.st.contStat[c][n].stat = SEAT_AT_THE_BENCH;                        /* the contestant is seating at the bench */
    fSt.st.contStat[c][n].strength = (unsigned int) floor (15.0*random ()/RAND_MAX+5.0);         /* set his strength */                                           /* no pieces were produced so far */
  }
  for (g = 0; g < G; g++)
  { for (t = 0; t < T; t++)
    { fSt.game[g].trial[t].pos = 0;                                       /* reset trial middle position of the rope */
      for (c = 0; c < C; c++)
      for (m = 0; m < M; m++)
        fSt.game[g].trial[t].id[c][m] = (unsigned int) -1;                           /* nobody has been selected yet */
    }
    fSt.game[g].pos = 0;                                                   /* reset game middle position of the rope */
    fSt.game[g].nTrial = (unsigned int) -1;                                              /* no trial has started yet */
  }
  fSt.nGame = (unsigned int) -1;                                                          /* no game has started yet */
  fSt.end = false;                                                             /* the simulation has not started yet */

  pthread_cond_init (&proceed, NULL);                                                  /* referee proceed sync point */
  for (c = 0; c < C; c++)
    pthread_cond_init (&waitForNotice[c], NULL);                      /* coaches waiting for notice sync point array */
  for (c = 0; c < C; c++)
  for (n = 0; n < N; n++)
    pthread_cond_init (&waitForCommand[c][n], NULL);             /* contestants waiting for command sync point array */
  nCoaches = 0;                                                     /* no coach has generated any inform request yet */
  nContestants = 0;                                                         /* no contestant has pulled the rope yet */
  for (c = 0; c < C; c++)
  { chooseTeam[c] = false;                             /* the referee has not request team formation for a trial yet */
    nContInPosition[c] = 0;                               /* no contestant is in position at his end of the rope yet */
    trialDecision[c] = false;                         /* no coach has received any notice about a trial decision yet */
  }
  for (c = 0; c < C; c++)
  for (n = 0; n < N; n++)
  { joinTheTeam[c][n] = false;                         /* the referee has not request team formation for a trial yet */
    startPulling[c][n] = false;                              /* no contestant is ready to start pulling the rope yet */
    returnToBench[c][n] = false;                                            /* no contestant has pulled the rope yet */
  }
  createLog (nFic);                                                                             /* log file creation */
  saveMatchHeader (nFic, &fSt);                                                                 /* save match header */
}
