all32:
			make -C debugging all
			make -C rawIO15 all
			make -C sofs15 all
			make -C syscalls15 all
			make -C showBlock15 all32
			make -C mkfs15 all32
			make -C testifuncs15 all32
			make -C mount15 all32

all64:
			make -C debugging all
			make -C rawIO15 all
			make -C sofs15 all
			make -C syscalls15 all
			make -C showBlock15 all64
			make -C mkfs15 all64
			make -C testifuncs15 all64
			make -C mount15 all64

clean:
			make -C debugging clean
			make -C rawIO15 clean
			make -C sofs15 clean
			make -C syscalls15 clean
			make -C showBlock15 clean
			make -C mkfs15 clean
			make -C testifuncs15 clean
			make -C mount15 clean
